import type { Metadata } from "next";
import { Cabin } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
// import ImageSlider from "./components/slider";
import { ThemeProvider } from "./components/themeProvider";


const roboto = Cabin({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Next JS APP - Antier",
    template: "%s | Antier"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={`d-flex flex-column h-100 ${roboto.className}`}>
          <Header />
          {/* <ImageSlider /> */}
          {children}
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
